# Generated by Django 4.1.7 on 2023-04-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_work_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.ImageField(default='', upload_to='image/%Y/%m/%d/'),
        ),
    ]
