# Generated by Django 4.1.7 on 2023-04-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_work_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='link',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='work',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(default='', upload_to='works/'),
        ),
    ]
