# Generated by Django 4.1.7 on 2023-04-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_work_link_alter_work_content_alter_work_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.CharField(default='', max_length=300),
        ),
    ]
