# Generated by Django 4.1.7 on 2023-04-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_work_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='image',
        ),
        migrations.AddField(
            model_name='work',
            name='cover',
            field=models.ImageField(default='', upload_to='user/works/'),
        ),
        migrations.AddField(
            model_name='work',
            name='images',
            field=models.FileField(default='', upload_to='user/works/'),
        ),
    ]
